# Generated by Django 4.2.7 on 2023-11-16 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('Produto', models.CharField(max_length=40)),
                ('Quantidade', models.IntegerField()),
                ('Preço', models.FloatField()),
                (
                    'Pagamento',
                    models.CharField(
                        choices=[
                            ('Dinheiro', 'Dinheiro'),
                            ('Cartão', 'Cartão'),
                        ],
                        max_length=10,
                    ),
                ),
                ('Total', models.FloatField(max_length=20)),
                ('Data_criação', models.DateField()),
                ('Vendedor', models.CharField(max_length=20)),
                ('Marca', models.CharField(max_length=30)),
            ],
        ),
    ]
