# Generated by Django 4.2.7 on 2023-11-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venda',
            old_name='Data_criação',
            new_name='Data_criacao',
        ),
        migrations.RenameField(
            model_name='venda',
            old_name='Preço',
            new_name='Preco',
        ),
        migrations.AlterField(
            model_name='venda',
            name='Vendedor',
            field=models.CharField(
                choices=[
                    ('Lukas', 'Lukas'),
                    ('Jsantos', 'Jsantos'),
                    ('Alison', 'Alison'),
                    ('Edvania', 'Edvania'),
                ],
                max_length=30,
            ),
        ),
    ]
