# Generated by Django 4.2.7 on 2023-11-16 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_rename_data_criação_venda_data_criacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='Total',
        ),
    ]
