# Generated by Django 4.2.7 on 2023-11-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_remove_venda_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='Pagamento',
            field=models.BooleanField(default=False),
        ),
    ]
