# Generated by Django 4.2.7 on 2023-11-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_alter_venda_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='Pagamento',
            field=models.CharField(
                choices=[('dinheiro', 'Dinheiro'), ('cartão', 'Cartão')],
                max_length=30,
            ),
        ),
    ]
